name: tests 

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: nodejs
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: bats install
      run: |
        git clone https://github.com/sstephenson/bats.git
        cd bats
        ./install.sh /usr/local
    - name: dependencies 
      run: |
        npm install
    - name: tests  
      run: npm test
